#!/bin/sh
. /etc/init.d/rc.functions
. /etc/rcS.conf
[ -s /etc/TZ ] && export TZ="$(cat /etc/TZ)"
echo "Processing /etc/init.d/rcS..."
echo -n "Mounting proc filesystem..."
mount proc
status
if [ "$EARLY_RUN_SCRIPTS" ]; then
	echo "Executing early initialization scripts..."
	for script in $EARLY_RUN_SCRIPTS
	do
		[ -x /etc/init.d/$script ] && /etc/init.d/$script
	done
fi
if [ "$LOAD_MODULES" ]; then
	echo -n "Loading modules..."
	depmod
	for mod in $LOAD_MODULES
	do
		echo -n " ${mod%%|*}"
		modprobe ${mod//|/ }
	done
	status
	[ "$KEEP_MODULES" ] || rm -rf /lib/modules 2> /dev/null
fi
echo -n "Mounting sys filesystem..."
mount sysfs
status
if [ -e /sbin/mdev ]; then
	echo -n "Start hotplug..."
	[ -e /proc/sys/kernel/hotplug ] &&
	echo /sbin/mdev > /proc/sys/kernel/hotplug
	mdev -s
	status
fi
if [ "$CHECK_FS" ]; then
	mount -o remount,ro /
	for i in $CHECK_FS
	do
		echo "Checking filesystem on : $i"
		e2fsck -p $i
	done
fi
echo "Remounting rootfs read/write..."
mount -o remount,rw /
echo "Mounting filesystems in fstab..."
mount -a
dmesg > /var/log/dmesg.log &
echo -n "Searching for early boot options..."
for opt in $(cat /proc/cmdline)
do
	case $opt in
		cdrom=*)
			export CDROM=${opt#cdrom=} ;;
		config=*)
			export CONFIG=${opt#config=} ;;
		*)
			continue ;;
	esac
done
status
if [ "$CLEAN_UP_SYSTEM" = "yes" ]; then
	echo -n "Cleaning up the system..."
	find /var/run -name "*.pid" -type f | xargs rm -f
	rm -rf /tmp /var/lock/*
	mkdir -p /tmp && chmod 1777 /tmp
	status
else
	echo "System clean up is disabled in /etc/rcS.conf..."
	echo -n "Keeping all tmp and pid files..."
	status
fi
if [  "$CDROM" ]; then
	DRIVE_NAME=${CDROM#/dev/}
else
	DRIVE_NAME=$(fgrep -s "drive name" /proc/sys/dev/cdrom/info | cut -f 3)
fi
if [ -n "$DRIVE_NAME" -a ! "$(readlink /dev/cdrom)" ]; then
	echo -n "Creating symlink : /dev/cdrom..."
	ln -s /dev/$DRIVE_NAME /dev/cdrom
	ln -s /dev/$DRIVE_NAME /dev/dvd
	chmod 0666 /dev/cdrom /dev/dvd /dev/$DRIVE_NAME
	status
fi
if ! fgrep -q "/dev/cdrom" /etc/fstab; then
	echo -n "Adding /dev/cdrom  to fstab..."
	echo '/dev/cdrom      /media/cdrom iso9660 user,ro,noauto       0       0' \
		>> /etc/fstab
	status
fi
if [ "$CONFIG" ]; then
	DEVICE=${CONFIG%,*}
	SCRIPT=${CONFIG#*,}
	echo "Probing $DEVICE... "
	if ! mount -r $DEVICE /mnt; then
		if echo $DEVICE | grep -Eq "/dev/sd|UUID=|LABEL="; then
			USBDELAY=$(cat /sys/module/usb_storage/parameters/delay_use)
			USBDELAY=$((1+$USBDELAY))
			echo "$DEVICE is potentially a USB device: sleep for $USBDELAY seconds"
			sleep $USBDELAY
		fi
		if ! mount -r $DEVICE /mnt; then
			CONFIG=""
		fi
	fi
	echo -n "Source $SCRIPT from $DEVICE..."
	if [ "$CONFIG" ]; then
		. /mnt/$SCRIPT
		umount /mnt 2> /dev/null || true
	fi
	status
fi
if [ -d /proc/bus/usb ]; then
	echo -n "Mounting /proc/bus/usb filesystem..."
	mount -t usbfs usbfs /proc/bus/usb
	status
fi
if [ "$KERNEL_LOG_DAEMONS" = "yes" ]; then
	echo -n "Starting system log deamon: syslogd..."
	syslogd -s $SYSLOGD_ROTATED_SIZE && status
	echo -n "Starting kernel log daemon: klogd..."
	klogd && status
else
	echo "Kernel log daemons are disabled in /etc/rc.conf..."
fi
[ -d /usr/share/kmap ] && echo -n "Load keymap..." &&
cat /usr/share/kmap/* | { /bin/loadkmap 2>/dev/null || loadkmap; } &&
rm -rf /usr/share/kmap && status
echo -n "Setting hostname..."
hostname -F /etc/hostname
status
echo "Executing all initialization scripts..."
for script in $RUN_SCRIPTS
do
	[ -x /etc/init.d/$script ] && /etc/init.d/$script
done
. /etc/rcS.conf
echo "Starting all daemons specified in /etc/rcS.conf..."
for daemon in $RUN_DAEMONS
do
	if [ -x /etc/init.d/$daemon ]; then
		/etc/init.d/$daemon start
	fi
done
if [  "$MESSAGE" ]; then
	reset
	echo -e "\033[1m$MESSAGE\033[0m"
fi
